# rebind <C-b> to <C-a>
set -g prefix C-a
unbind C-b

# Basic improvements
set -g mouse on
set -g base-index 1
set -w -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 10000
set -s escape-time 0

# add plugins
set -g @catppuccin_window_tabs_enabled on
